---
title: "Getting Started with `pins` on RStudio Connect"
author: "Katie Masiello"
date: "2/5/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pins)
```

## What is the `pins` package?
Pins is an R package that makes it possible to remotely save (“pin”) any object serializable by R, like a data frame or model object. These objects are saved to a “board” such as RStudio Connect. Once a pin is deployed to RStudio Connect, you can use the standard RStudio Connect access controls to share it with others.


* What the package does  
* current release version as of time of writing, where to get the package  
* getting started, how tos  
* examples, and what can be your first project with this  
* why would I use this?  
* any enterprise considerations  
* am I reliant on anyone or anything else to be successful?  
* where do i go for help?  
*  additional resources

kelly's ideas:
automate 
offer a blank blog template for a customer to publish on their own connect server as long as that server was connected to the internet.  Create Katie's CSS RSS feed that that blank template runs on a scheudle to pull down news articles and things I want them to know about.  Their template executes on their server and pulls in the information that I Want to push and it populates that document.  and it gets set up to send an email to anyone at their organization that opts in. 
I have one place to update info, they opt in.   and they dont have to email internally. 

## Connecting to RStudio Connect
