---
title: "Instructions"
author: "Elena Ruiz and Katie Masiello" 
date: "3/20/2020"
output: html_document
---

Before I can publish a pin to the RSC board, I have to get an API key from Connect and save this to my sys environment variables.  

1. In RSC, generate an API key.  I named this "forusingpins" and copied the value to the clipboard  
2. now in R I have to save this API key to my system environment variables.  Since I want this to persist and not evaporate every time R restarts, I need to write this in my .Rprofile. Think about if you want this to be in your Project .Rproject file or your home directory .Rprofile. 
Do this with: 
`Sys.setenv("RSC_API_KEY" = <paste key here>)`
3. Now I register the board, which isn't initializing a new board, it's just telling my session that there's a place we can stick stuff.  "register" means I see you and know you're there, it's not creating somethign from nothing. Use `pins::board_register(
    "rsconnect", 
    server = "https://colorado.rstudio.com/rsc/",
    key = Sys.getenv("RSC_API_KEY")
    )`  
4. stick your object on the rsconnect board with `pin(lego_set_data, description = "LEGO set data", board = "rsconnect")`  
5. OMG, it worked!  
6. retrieve the pin with the code provided in RSC `setsData <- pin_get("katie/lego-set-data", board = "rsconnect")`

7. Publishing - the first time you publish, it will fail saying "[Connect] Message: 'Invalid API key, the API key is empty.'"  because there is no key on the environment variable on connect.  Go drop RSC_API_KEY in environment variables and refresh.